### ISSUE TITLE
Archetypes build failures due to missing libraries

### ISSUE THREAD

**Issue by AlexanderBouwens** [automatiko-io/automatiko-engine#359] opened 2023-11-23 09:54 UTC
When using the maven automatiko-archetype to create a maven module the creation of the module succeeds, but a build with `mvn clean install ` fails due to missing libraries:

![automatiko build failure](https://github.com/automatiko-io/automatiko-engine/assets/5717646/5e14ba9c-bedf-47d8-bd96-fc6b4e556db9)

adding the following missing jakarta libraries will resolve the issue:

![automatiko build failure 2](https://github.com/automatiko-io/automatiko-engine/assets/5717646/5a69b040-be5d-445a-bf39-14157d73c340)

**Comment by mswiderski** [comment] 2023-11-23 10:47
this is a bit weird as it has the bom imported and all these dependencies should come from there. Would you mind sharing the pom.xml that was generated?

**Comment by AlexanderBouwens** [comment] 2023-11-23 13:47
Here is the POM:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <artifactId>hidden</artifactId>
    <groupId>hidden</groupId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <groupId>hidden</groupId>
  <artifactId>wf-temp</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <name>Generated project wf-temp</name>
  <description>Generated description for wf-temp</description>

  <properties>
    <quarkus.version>3.4.0</quarkus.version>
    <automatiko.version>0.32.0</automatiko.version>
    <surefire.version>2.22.1</surefire.version>
    <compiler.version>3.8.1</compiler.version>

    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.source>11</maven.compiler.source>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.automatiko.quarkus</groupId>
        <artifactId>automatiko-quarkus-bom</artifactId>
        <version>${automatiko.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.automatiko.quarkus</groupId>
      <artifactId>automatiko-service</artifactId>
    </dependency>
    
    
    <dependency>
      <groupId>io.automatiko.addons</groupId>
      <artifactId>automatiko-process-management-addon</artifactId>
    </dependency>
    
    
    
    
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.1</version>
        <configuration>
          <systemProperties>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemProperties>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.22.1</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
        <quarkus.native.additional-build-args>--report-unsupported-elements-at-runtime</quarkus.native.additional-build-args>
      </properties>
    </profile>
    <profile>
      <id>container</id>
      <activation>
        <property>
          <name>container</name>
        </property>
      </activation>
      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-container-image-jib</artifactId>
        </dependency>
      </dependencies>
      <properties>
        <quarkus.container-image.build>true</quarkus.container-image.build>
      </properties>
    </profile>
    <profile>
      <id>container-native</id>
      <activation>
        <property>
          <name>container-native</name>
        </property>
      </activation>
      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-container-image-jib</artifactId>
        </dependency>
      </dependencies>
        <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.22.1</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
        <quarkus.native.additional-build-args>--report-unsupported-elements-at-runtime</quarkus.native.additional-build-args>
        <quarkus.native.container-build>true</quarkus.native.container-build>
        <quarkus.container-image.build>true</quarkus.container-image.build>
        <quarkus.container-image.insecure>true</quarkus.container-image.insecure>
      </properties>
    </profile>
    <profile>
      <id>kubernetes</id>
      <activation>
        <property>
          <name>kubernetes</name>
        </property>
      </activation>
      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-kubernetes</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-container-image-jib</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
      </dependencies>
      <properties>
        <quarkus.container-image.build>true</quarkus.container-image.build>
        <quarkus.kubernetes.image-pull-policy>IfNotPresent</quarkus.kubernetes.image-pull-policy>
      </properties>
    </profile>
    <profile>
      <id>kubernetes-native</id>
      <activation>
        <property>
          <name>kubernetes-native</name>
        </property>
      </activation>
      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-kubernetes</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-container-image-jib</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
      </dependencies>
        <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.22.1</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
        <quarkus.native.additional-build-args>--report-unsupported-elements-at-runtime</quarkus.native.additional-build-args>
        <quarkus.native.container-build>true</quarkus.native.container-build>
        <quarkus.container-image.build>true</quarkus.container-image.build>
        <quarkus.container-image.insecure>true</quarkus.container-image.insecure>
        <quarkus.kubernetes.image-pull-policy>IfNotPresent</quarkus.kubernetes.image-pull-policy>
      </properties>
    </profile>
  </profiles>

</project>

**Comment by mswiderski** [comment] 2023-11-23 16:25
just build on this pom without any issues. The only thing I did was to remove the parent declaration. Could it be that the parent has something in it that causes quarkus to be confused? Maybe different version of quarkus is being used?

**Comment by AlexanderBouwens** [comment] 2023-11-24 08:48
We do not use quarkus in the parent pom, however we have defined dependencies on the jakarta libraries in the parent pom.

**Comment by mswiderski** [comment] 2023-11-24 09:53
can you confirm that without the parent declaration it works?

**Comment by AlexanderBouwens** [comment] 2023-11-24 10:27
To test that I've create a new clean project and ran the archetype.
Now i get the following exception:
![automatiko build failure 3](https://github.com/automatiko-io/automatiko-engine/assets/5717646/121ba61e-706e-4553-8841-5755de950b2d)

**Comment by mswiderski** [comment] 2023-11-24 11:28
this looks like some windows path issue, never seen it before, will need to find a windows machine to reproduce it.

**Comment by mswiderski** [comment] 2023-11-28 12:11
indeed there was an issue with paths on windows. It is now fixed on main branch and I plan to publish new release in like 2 weeks or so. Would you mind testing from main branch?

if that would would mean:
- clone the automatiko-engine repo
- build with `mvn clean install -DskipTests`
- update your project pom.xml with automatiko version set to `0.0.0-SNAPSHOT` and quarkus version set to '3.5.3'

**Comment by mswiderski** [comment] 2024-01-03 06:24
fixed and released as part of 0.33.0

**Closed by mswiderski** 2024-01-03 06:24 UTC
